### ISSUE TITLE
CI fails

### ISSUE THREAD

**Issue by gerdoe-jr** [gerdoe-jr/tw-econ#10]
@Anime-pdf, any thoughts?

**Comment by pmakin** [comment]
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v1`. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/

Use upload-artifact@v3 or upload-artifact@v4. v3 is scheduled for deprecation on November 30, 2024
